### PR TITLE
Precompute transitive dependencies

### PR DESCRIPTION
**Pull request by DevinR528**
I was trying to push up to ask what you thought of this
```rust
// the is inside process_event after removing found crates and pinning version numbers

// this could probably be a FnvHashSet instead might save a few iterations
let mut to_update = Vec::new();

let index = self.crates.entry(event.name).or_insert_with(Vec::new).len();
let key = CrateKey::new(event.name, index as u32);

// the updated crates dep's and trans dep's from Resolve::add_crate 
// passed along from resolve_and_add_to_graph
let trans_res = self.resolve_and_add_to_graph(key, &metadata);
to_update.extend(trans_res.crates.keys());

self.reverse_depends.insert(key, Set::default());
self.crates.get_mut(&event.name).unwrap().push(metadata);

for outdated in redo.iter() {
    let metadata = self.crates[&outdated.name][outdated.index as usize].clone();
    warn!("re-resolving {} {}", outdated.name, metadata.num);

    // do I need to also recheck the redo crates??
    let re_res = self.resolve_and_add_to_graph(*outdated, &metadata);
    to_update.extend(re_res.crates.keys());
}
// returns only the updated crates to re count transitive deps at every
// time point they changed
to_update
```
so I'm only looping over crates that I have to recount because of update right? If this is the way to
do it it's been running for 3 days and is at 50%, I also ran this on the first 2 months of  the crates.io index and got 3 million unique events??

### CODE REVIEW

**Comment by DevinR528** [comment]
I may have figured it out its 55% in 3 hours I'll let you know in the morning hopefully.

I filtered the `update` `HashSet` by making sure it was a crate contained in `Universe.crates`.

**Comment by DevinR528** [comment]
serde-graph08-1-1

Yay!! It mostly worked :laughing:  finally. There are odd outliers, the 3rd and 4th. Ignore the `direct_count` this struct will look different anyways, instead of a count it'll have a `Vec<Krate>` where `Krate` is version and name.
```
TranitiveDep {name: "serde", timestamp: 2019-06-21T01:34:06Z, version: Version { major: 1, minor: 0, patch: 92, pre: [], build: [] }, transitive_count: 6885, direct_count: 4820, total: 26902 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T02:14:09Z, version: Version { major: 1, minor: 0, patch: 92, pre: [], build: [] }, transitive_count: 6885, direct_count: 4820, total: 26903 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T02:14:09Z, version: Version { major: 1, minor: 0, patch: 89, pre: [], build: [] }, transitive_count: 15, direct_count: 4820, total: 26903 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T02:14:09Z, version: Version { major: 1, minor: 0, patch: 37, pre: [], build: [] }, transitive_count: 2, direct_count: 4820, total: 26903 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T02:14:09Z, version: Version { major: 0, minor: 8, patch: 23, pre: [], build: [] }, transitive_count: 338, direct_count: 4820, total: 26903 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T02:15:33Z, version: Version { major: 1, minor: 0, patch: 92, pre: [], build: [] }, transitive_count: 6885, direct_count: 4820, total: 26903 }
TranitiveDep { name: "serde", timestamp: 2019-06-21T03:43:34Z, version: Version { major: 1, minor: 0, patch: 92, pre: [], build: [] }, transitive_count: 6886, direct_count: 4820, total: 26905 }
```
It only took 6 hours to compute the entire graph so not to bad, unfortunately the gzipped file is 170MB although I could remove all sequenced duplicate counts which would probably at least halve it if not more?

**Comment by dtolnay** [comment]
Nice, that looks promising.

170MB is substantially more than my back of the envelope estimates. Could you share just a few lines from near the middle of the data? I am curious where the extra size is coming from.

What do you mean by sequenced duplicate counts?

**Comment by DevinR528** [comment]
By sequenced duplicates I meant for example `serde:1.0` if it had 10 entries in a row that were had the same transitive/direct dependency counts you would only need one for the graph. I realize that this is most likely the problem with the gziped precomputed files size, if I'm only recomputing updated/changed crates I should not get a bunch of duplicates in a row (not actually in a row but compared to the last occurrence of itself). 

I was able to find an example of the duplicate problem `libc`
```
{"name":"libc","timestamp":"2018-11-05T07:01:30Z","version":"0.2.43","transitive_count":11285,"direct_count":2350,"total":19953}
{"name":"string_cache_codegen","timestamp":"2018-11-05T07:01:30Z","version":"0.4.2","transitive_count":128,"direct_count":4,"total":19953}
{"name":"unicode-normalization","timestamp":"2018-11-05T07:01:30Z","version":"0.1.7","transitive_count":2776,"direct_count":38,"total":19953}
{"name":"foreign-types","timestamp":"2018-11-05T07:01:30Z","version":"0.3.2","transitive_count":1774,"direct_count":14,"total":19953}
{"name":"unicase","timestamp":"2018-11-05T07:01:30Z","version":"1.4.2","transitive_count":1624,"direct_count":41,"total":19953}
{"name":"tokio-codec","timestamp":"2018-11-05T07:01:30Z","version":"0.1.1","transitive_count":1437,"direct_count":45,"total":19953}
{"name":"arrayvec","timestamp":"2018-11-05T07:01:30Z","version":"0.4.7","transitive_count":2459,"direct_count":93,"total":19953}
{"name":"num-traits","timestamp":"2018-11-05T07:06:33Z","version":"0.2.6","transitive_count":4555,"direct_count":424,"total":19953}
{"name":"num-integer","timestamp":"2018-11-05T07:06:33Z","version":"0.1.39","transitive_count":3379,"direct_count":41,"total":19953}
{"name":"lunardate","timestamp":"2018-11-05T07:06:33Z","version":"0.1.4","transitive_count":0,"direct_count":0,"total":19953}
{"name":"redox_syscall","timestamp":"2018-11-05T07:06:33Z","version":"0.1.40","transitive_count":6137,"direct_count":19,"total":19953}
{"name":"chrono","timestamp":"2018-11-05T07:06:33Z","version":"0.4.6","transitive_count":1851,"direct_count":958,"total":19953}
{"name":"libc","timestamp":"2018-11-05T07:06:33Z","version":"0.2.43","transitive_count":11285,"direct_count":2350,"total":19953}
```
My guess is that recomputing the `let mut redo = Set::default` from `Universe::process_event` is adding unnecessary duplicate entries to the final json file? I'm re-running it now to check this.

**Comment by DevinR528** [comment]
ser-1
I removed the re computation of `redo` so that helped down to 57MB. Still trying to figure out where the dips come in.

**Comment by DevinR528** [comment]
You were exactly right check [this](https://github.com/holochain/lib3h/blob/edge/crates/lib3h/Cargo.toml) out!

**Comment by DevinR528** [comment]
serde
Here is the graph with data from the index that is current

**Comment by DevinR528** [comment]
serde
🎉 🎆 

```rust
let unpinned_ver = if dep.req.to_string().contains('=') {
    VersionReq::from_str(&dep.req.to_string().split('=').last().unwrap().trim()).unwrap()
} else {
    dep.req.clone()
};
```
I'd imagine there is a better way to do this but this works for now!
Thanks for sitting down with me I enjoyed rust conf.

**Comment by DevinR528** [comment]
Well I've hit another wall. I first created a struct
```rust
struct Krate {
    name: String,
    version: Version
}
pub struct TransitiveDep {
    pub name: String,
    pub timestamp: DateTime,
    pub version: Version,
    pub transitive_count: Vec<Krate>,
    pub direct_count: Vec<Krate>,
    pub total: usize,
}
```
I also tried making `version` a string. Building up the TransitiveDep this way crashed with `SIGKILL` at 10% everytime, I'm not entirely sure what happened but my guess is it ran out of memory. Writing this struct using a `BufWriter` to a file while creating it (in side the for loop and dropping after writing) worked but because it was compresing a chunk at a time even at the highest compression rate 50% was almost 100GB. Next attempt I created a mapping
```rust
pub struct CrateLegend(PreHashedMap<u64, usize>);
impl CrateLegend {
    // inserts key of hashed crate name and version
    pub fn insert(&mut self, key: &str, version: &Version) {
        let k = fnv_key((&key, &version));
        *self.0.entry(k).or_insert(0) += 1;
    }
}
pub struct TransitiveDep {
    pub name: String,
    pub timestamp: DateTime,
    pub version: Version,
    pub transitive_count: CrateLegend,
    pub total: usize,
}
```
this crashed with the same error at 22% writing on the fly also results in a huge file a gig at ~20%.
In order to get `--exclude` working we have to save this information I'm just not sure how, my only other idea is to fall back to your original way of computing the counts if the `--exclude` flag is passed?

**Comment by dtolnay** [comment]
Thanks for your work on this! I ended up going with a different approach in #30 that doesn't involve the precomputation, but still performs significantly better by parallelizing better.

**Comment by DevinR528** [comment]
Ooo nice, that `differential_dataflow` crate looks cool!

**Pull request closed without merging**
