### PR TITLE
Show percentages in y axis in relative mode

### LINKED ISSUE #23: Show percentages on the vertical axis in relative mode
4.5% instead of 0.045.

### PR DESCRIPTION
**Pull request by VasanthakumarV**
Closes #23 

__Relative__

tally-relative

__Absolute__

tally-absolute

### CODE REVIEW

**Review by dtolnay — CHANGES_REQUESTED** [review]
Thanks for the PR!

Is it possible to set the precision automatically based on the tick interval? Hardcoding to 2 digits is inappropriate for big or small percentages.

Screenshot from 2021-09-07 13-52-47
Screenshot from 2021-09-07 13-53-01

**Comment by VasanthakumarV** [comment]
@dtolnay Now the precision value is not hard-coded.

But since the same formatter is used for both the y-axis and the tooltip, the y-axis ticks might have _one additional precision_ than necessary (the tooltips require finer precision than the axis).

The upside to this is, every y-axis value will have the same precision everywhere.

This can be easily remedied by having two formatters, but wasn't sure if the additional complexity is required.

<table>
  <tr>
    <td>anyhow</td>
    <td>eyre</td>
  </tr>
  <tr>
    <td>regex</td>
    <td>serde</td>
  </tr>
</table>

**Comment by VasanthakumarV** [comment]
It is also possible to remove any insignificant trailing zeros from everywhere using a single d3 formatter, but it can make numbers non-aligned and they will jump around when we move the mouse.

i.e.

1%
0.9%

vs

1.0%
0.9%

**Comment by VasanthakumarV** [comment]
Added a separate formatter for the tooltip, so that we avoid the non-significant zeros in the y axis

 <table>
  <tr>
    <td>anyhow</td>
    <td>eyre</td>
  </tr>
  <tr>
    <td>regex</td>
    <td>serde</td>
  </tr>
</table>

**Review by dtolnay — APPROVED** [review]
Thanks! &mdash; the examples I tried all look good to me now.

**Pull request merged**
